#!/usr/bin/env python3
"""Small helper for Reddit Ads API OAuth and smoke tests.

Stores local auth state under ``$TAKYON_HOME/secrets`` so the credentials stay
out of tracked repo files while still being easy to reuse from this workspace.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TAKYON_HOME = Path(os.getenv("TAKYON_HOME") or (REPO_ROOT / ".takyon"))
DEFAULT_STATE_PATH = DEFAULT_TAKYON_HOME / "secrets" / "reddit_ads.json"
DEFAULT_ENV_PATH = DEFAULT_TAKYON_HOME / "secrets" / "reddit_ads.env"
TOKEN_URL = "https://www.reddit.com/api/v1/access_token"
API_BASE = "https://ads-api.reddit.com/api/v3"


def _json_dump(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=True)


def _now() -> int:
    return int(time.time())


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _write_private_text(path: Path, text: str) -> None:
    _ensure_parent(path)
    path.write_text(text, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def _load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _save_state(path: Path, state: dict[str, Any]) -> None:
    _write_private_text(path, _json_dump(state) + "\n")


def _save_env(path: Path, state: dict[str, Any]) -> None:
    env_map = {
        "REDDIT_ADS_CLIENT_ID": state.get("client_id", ""),
        "REDDIT_ADS_CLIENT_SECRET": state.get("client_secret", ""),
        "REDDIT_ADS_REDIRECT_URI": state.get("redirect_uri", ""),
        "REDDIT_ADS_BUSINESS_ID": state.get("business_id", ""),
        "REDDIT_ADS_ACCOUNT_ID": state.get("ad_account_id", ""),
        "REDDIT_ADS_USERNAME": state.get("username", ""),
        "REDDIT_ADS_USER_AGENT": state.get("user_agent", ""),
        "REDDIT_ADS_SCOPE": state.get("scope", ""),
        "REDDIT_ADS_ACCESS_TOKEN": state.get("access_token", ""),
        "REDDIT_ADS_REFRESH_TOKEN": state.get("refresh_token", ""),
        "REDDIT_ADS_TOKEN_EXPIRES_AT": str(state.get("expires_at", "")),
    }
    lines = ["# Generated by hermes-agent-main/scripts/reddit_ads_api.py"]
    for key, value in env_map.items():
        safe = str(value).replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{safe}"')
    _write_private_text(path, "\n".join(lines) + "\n")


def _state_user_agent(state: dict[str, Any]) -> str:
    explicit = str(state.get("user_agent") or "").strip()
    if explicit:
        return explicit
    username = str(state.get("username") or "litebulbapp").strip() or "litebulbapp"
    client_id = str(state.get("client_id") or "redditads").strip() or "redditads"
    return f"desktop:{client_id}:v1 (by /u/{username})"


def _token_request(
    *,
    client_id: str,
    client_secret: str,
    form_data: dict[str, str],
    user_agent: str,
) -> dict[str, Any]:
    auth = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("ascii")
    body = urllib.parse.urlencode(form_data).encode("utf-8")
    req = urllib.request.Request(
        TOKEN_URL,
        data=body,
        headers={
            "Authorization": f"Basic {auth}",
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": user_agent,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"Token exchange failed ({exc.code}): {detail}") from exc
    return json.loads(raw)


def _api_request(
    *,
    state: dict[str, Any],
    path: str,
    method: str = "GET",
    json_body: dict[str, Any] | None = None,
) -> tuple[int, dict[str, str], Any]:
    token = _ensure_access_token(state_path=Path(state["_state_path"]), env_path=Path(state["_env_path"]))
    headers = {
        "Authorization": f"Bearer {token}",
        "User-Agent": _state_user_agent(state),
        "Accept": "application/json",
    }
    body: bytes | None = None
    if json_body is not None:
        body = json.dumps(json_body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    url = path if path.startswith("http://") or path.startswith("https://") else f"{API_BASE}{path}"
    req = urllib.request.Request(url, data=body, headers=headers, method=method.upper())
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = resp.read().decode("utf-8")
            content_type = resp.headers.get("Content-Type", "")
            data: Any
            if "json" in content_type:
                data = json.loads(payload)
            else:
                data = payload
            return resp.getcode(), dict(resp.headers.items()), data
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"API request failed ({exc.code}) for {url}: {detail}") from exc


def _ensure_access_token(*, state_path: Path, env_path: Path) -> str:
    state = _load_state(state_path)
    if not state:
        raise SystemExit(f"No Reddit Ads auth state found at {state_path}")
    expires_at = int(state.get("expires_at") or 0)
    access_token = str(state.get("access_token") or "").strip()
    if access_token and expires_at > _now() + 120:
        return access_token
    refresh_token = str(state.get("refresh_token") or "").strip()
    if not refresh_token:
        raise SystemExit("Stored Reddit Ads auth state does not include a refresh token.")
    payload = _token_request(
        client_id=str(state["client_id"]),
        client_secret=str(state["client_secret"]),
        form_data={"grant_type": "refresh_token", "refresh_token": refresh_token},
        user_agent=_state_user_agent(state),
    )
    state["access_token"] = payload["access_token"]
    state["refresh_token"] = payload.get("refresh_token", refresh_token)
    state["scope"] = payload.get("scope", state.get("scope", ""))
    state["token_type"] = payload.get("token_type", "bearer")
    state["expires_in"] = int(payload.get("expires_in") or 0)
    state["expires_at"] = _now() + state["expires_in"]
    _save_state(state_path, state)
    _save_env(env_path, state)
    return str(state["access_token"])


def cmd_exchange(args: argparse.Namespace) -> int:
    state = _load_state(args.state_path)
    client_id = args.client_id or state.get("client_id")
    client_secret = args.client_secret or state.get("client_secret")
    redirect_uri = args.redirect_uri or state.get("redirect_uri")
    if not client_id or not client_secret or not redirect_uri:
        raise SystemExit("exchange requires client_id, client_secret, and redirect_uri")
    username = args.username or state.get("username") or "litebulbapp"
    user_agent = args.user_agent or state.get("user_agent") or f"desktop:{client_id}:v1 (by /u/{username})"
    payload = _token_request(
        client_id=str(client_id),
        client_secret=str(client_secret),
        form_data={
            "grant_type": "authorization_code",
            "code": args.code,
            "redirect_uri": str(redirect_uri),
        },
        user_agent=str(user_agent),
    )
    state.update(
        {
            "client_id": str(client_id),
            "client_secret": str(client_secret),
            "redirect_uri": str(redirect_uri),
            "business_id": args.business_id or state.get("business_id", ""),
            "ad_account_id": args.ad_account_id or state.get("ad_account_id", ""),
            "username": str(username),
            "app_name": args.app_name or state.get("app_name", "LiteBulb Ads API"),
            "user_agent": str(user_agent),
            "access_token": payload["access_token"],
            "refresh_token": payload.get("refresh_token", ""),
            "token_type": payload.get("token_type", "bearer"),
            "scope": payload.get("scope", ""),
            "expires_in": int(payload.get("expires_in") or 0),
            "expires_at": _now() + int(payload.get("expires_in") or 0),
        }
    )
    _save_state(args.state_path, state)
    _save_env(args.env_path, state)
    print(
        _json_dump(
            {
                "saved_state": str(args.state_path),
                "saved_env": str(args.env_path),
                "business_id": state.get("business_id", ""),
                "ad_account_id": state.get("ad_account_id", ""),
                "scope": state.get("scope", ""),
                "expires_at": state.get("expires_at", 0),
            }
        )
    )
    return 0


def cmd_refresh(args: argparse.Namespace) -> int:
    token = _ensure_access_token(state_path=args.state_path, env_path=args.env_path)
    state = _load_state(args.state_path)
    print(
        _json_dump(
            {
                "saved_state": str(args.state_path),
                "saved_env": str(args.env_path),
                "access_token_present": bool(token),
                "expires_at": state.get("expires_at", 0),
                "scope": state.get("scope", ""),
            }
        )
    )
    return 0


def cmd_request(args: argparse.Namespace) -> int:
    state = _load_state(args.state_path)
    state["_state_path"] = str(args.state_path)
    state["_env_path"] = str(args.env_path)
    json_body = json.loads(args.data) if args.data else None
    status, headers, data = _api_request(state=state, path=args.path, method=args.method, json_body=json_body)
    output = {"status": status, "data": data}
    if args.include_headers:
        output["headers"] = {
            key: value
            for key, value in headers.items()
            if key.lower().startswith("ratelimit") or key.lower() in {"content-type", "x-request-id"}
        }
    print(_json_dump(output))
    return 0


def cmd_smoke(args: argparse.Namespace) -> int:
    state = _load_state(args.state_path)
    state["_state_path"] = str(args.state_path)
    state["_env_path"] = str(args.env_path)
    checks: dict[str, Any] = {}
    checks_to_run = [
        ("me", "/me"),
        ("business", f"/businesses/{state['business_id']}" if state.get("business_id") else ""),
        (
            "ad_accounts_by_business",
            f"/businesses/{state['business_id']}/ad_accounts" if state.get("business_id") else "",
        ),
        ("ad_account", f"/ad_accounts/{state['ad_account_id']}" if state.get("ad_account_id") else ""),
    ]
    for label, path in checks_to_run:
        if not path:
            continue
        try:
            status, headers, data = _api_request(state=state, path=path, method="GET")
            checks[label] = {
                "status": status,
                "rate_limit": headers.get("RateLimit"),
                "rate_limit_policy": headers.get("RateLimit-Policy"),
                "keys": sorted(list(data.keys()))[:20] if isinstance(data, dict) else None,
            }
        except SystemExit as exc:
            checks[label] = {"error": str(exc)}
    print(_json_dump(checks))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--state-path", type=Path, default=DEFAULT_STATE_PATH)
    parser.add_argument("--env-path", type=Path, default=DEFAULT_ENV_PATH)
    sub = parser.add_subparsers(dest="command", required=True)

    exchange = sub.add_parser("exchange", help="Exchange an auth code for tokens and save local state.")
    exchange.add_argument("--code", required=True)
    exchange.add_argument("--client-id")
    exchange.add_argument("--client-secret")
    exchange.add_argument("--redirect-uri")
    exchange.add_argument("--business-id")
    exchange.add_argument("--ad-account-id")
    exchange.add_argument("--username")
    exchange.add_argument("--user-agent")
    exchange.add_argument("--app-name")
    exchange.set_defaults(func=cmd_exchange)

    refresh = sub.add_parser("refresh", help="Refresh stored access token if needed.")
    refresh.set_defaults(func=cmd_refresh)

    request = sub.add_parser("request", help="Make a Reddit Ads API request with saved auth.")
    request.add_argument("path", help="API path like /me or full URL")
    request.add_argument("--method", default="GET")
    request.add_argument("--data", help="JSON request body string")
    request.add_argument("--include-headers", action="store_true")
    request.set_defaults(func=cmd_request)

    smoke = sub.add_parser("smoke", help="Run a read-only auth smoke test.")
    smoke.set_defaults(func=cmd_smoke)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
